#!/usr/bin/env python3
"""Generate a SHA-256 manifest for replication-package files.

The manifest covers repository materials in data, prompts, analysis, docs, and
outputs, excluding hidden files, temporary Office files, version-control
directories, environment files, secret-like files, and common operating-system
metadata files.
"""

from __future__ import annotations

import csv
import hashlib
import re
from datetime import datetime, timezone
from pathlib import Path


REPOSITORY_SUBDIRS = ("data", "prompts", "analysis", "docs", "outputs")
MANIFEST_PATH = Path("hashes") / "sha256_manifest.csv"

# Common directories and files that should not be part of a replication
# integrity manifest.
EXCLUDED_DIR_NAMES = {
    ".git",
    "__pycache__",
}

EXCLUDED_FILENAMES = {
    ".DS_Store",
    ".env",
    "Thumbs.db",
    "desktop.ini",
}

# Microsoft Office lock/temp files usually begin with "~$".
EXCLUDED_PREFIXES = ("~$",)

# Generated bytecode files are environment-specific and not research inputs.
EXCLUDED_SUFFIXES = {
    ".env",
    ".key",
    ".pem",
    ".pyc",
    ".pyo",
    ".p12",
    ".pfx",
}

# Exclude filenames that commonly contain credentials or private access
# material. This is intentionally conservative for public replication archives.
SECRET_NAME_PATTERN = re.compile(
    r"(api[_-]?key|access[_-]?token|auth[_-]?token|bearer[_-]?token|"
    r"credential|credentials|secret|password|passwd|private[_-]?key|"
    r"id_rsa|id_dsa|id_ecdsa|id_ed25519)",
    re.IGNORECASE,
)


def is_hidden_path(path: Path) -> bool:
    """Return True if any part of a path is hidden."""
    return any(part.startswith(".") for part in path.parts)


def should_exclude(path: Path) -> bool:
    """Return True when a file should be skipped."""
    if is_hidden_path(path):
        return True

    if any(part in EXCLUDED_DIR_NAMES for part in path.parts):
        return True

    if path.name in EXCLUDED_FILENAMES:
        return True

    if SECRET_NAME_PATTERN.search(path.name):
        return True

    if path.name.startswith(EXCLUDED_PREFIXES):
        return True

    if path.suffix in EXCLUDED_SUFFIXES:
        return True

    return False


def sha256_file(path: Path) -> str:
    """Compute a file's SHA-256 hash without loading the whole file at once."""
    digest = hashlib.sha256()
    with path.open("rb") as file_obj:
        for chunk in iter(lambda: file_obj.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def utc_mtime(path: Path) -> str:
    """Return the file modification time as an ISO-8601 UTC timestamp."""
    modified = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
    return modified.isoformat().replace("+00:00", "Z")


def iter_manifest_files(repo_root: Path) -> list[Path]:
    """Find all files in the configured repository subdirectories."""
    files: list[Path] = []

    for subdir in REPOSITORY_SUBDIRS:
        root = repo_root / subdir
        if not root.exists():
            continue

        for path in root.rglob("*"):
            relative_path = path.relative_to(repo_root)
            if path.is_file() and not should_exclude(relative_path):
                files.append(relative_path)

    return sorted(files, key=lambda path: path.as_posix())


def write_manifest(repo_root: Path, files: list[Path]) -> None:
    """Write the SHA-256 manifest CSV."""
    manifest_path = repo_root / MANIFEST_PATH
    manifest_path.parent.mkdir(parents=True, exist_ok=True)

    with manifest_path.open("w", newline="", encoding="utf-8") as csv_file:
        writer = csv.DictWriter(
            csv_file,
            fieldnames=[
                "file_path",
                "sha256",
                "file_size_bytes",
                "last_modified_utc",
            ],
        )
        writer.writeheader()

        for relative_path in files:
            absolute_path = repo_root / relative_path
            stat = absolute_path.stat()
            writer.writerow(
                {
                    "file_path": relative_path.as_posix(),
                    "sha256": sha256_file(absolute_path),
                    "file_size_bytes": stat.st_size,
                    "last_modified_utc": utc_mtime(absolute_path),
                }
            )


def main() -> None:
    """Generate the manifest and print a concise summary."""
    repo_root = Path(__file__).resolve().parents[2]
    files = iter_manifest_files(repo_root)
    write_manifest(repo_root, files)

    print(f"SHA-256 manifest written to {MANIFEST_PATH.as_posix()}")
    print(f"Files hashed: {len(files)}")


if __name__ == "__main__":
    main()
